name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    uses: lirios/.github/.github/workflows/build-linux.yml@master
